http_server:
  address: "0.0.0.0"
  port: "8080"
database:
  address: "postgres://user:password@postgres:5432/database"
redis:
  address: "redis:6379"
  password: ""
  db: 0
jwt_secret_key: "VdR?jmaR)+#i71Y"